can work on rails > 7.0
dhyegocalota/active_record-humanized_enum pull request #2
Opened 2022-09-14 09:40 UTC by Wolfer

In Rails v7 the enum method has a different list of arguments

2022-09-20 13:15 UTC, dhyegocalota commented
Hi @Wolfer! Thank you for your contribution. I'll review it very soon so we can merge and release a new version.

2022-09-28 11:48 UTC, dhyegocalota requested changes
Great work @Wolfer! Thank you for your contribution! 

I'll merge this PR and release a new version as soon as you apply this small change requested.

2022-09-28 11:48 UTC, dhyegocalota commented on active_record-humanized_enum.gemspec
> +  spec.add_dependency 'railties', ">= 7.0"
It works with Rails versions up to 4.

```suggestion
  spec.add_dependency 'railties', '>= 4.0'
```

2022-09-28 11:53 UTC, Wolfer commented on active_record-humanized_enum.gemspec
> +  spec.add_dependency 'railties', ">= 7.0"
commited. Thanks for the clarification

2022-09-28 11:58 UTC, merged